'on':
  github:
    branches:
      only: main
jobs:
  Install:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: script@v1
    with:
      script: |
        sudo apt-get update
        sudo apt-get upgrade
