'on':
  github:
    branches:
      only: main
jobs:
  Install:
    ressources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: script@v1
    with:
      script: |
        sudo apt-get update
        sudo apt-get upgrade

  Build:
    ressources:
      instance-type: C5 
    needs:
      - Install
    outputs:
      repo:
        type: volume
    inputs:
      repo: Install.outputs.repo
    uses: script@v1
    with:
      script: |
        sudo apt-get update
        sudo apt-get upgrade

  Run:
    ressources:
      instance-type: A100
    needs:
      - Build
    inputs:
      repo: Build.outputs.repo
    uses: script@v1
    with:
      script: |
        sudo apt-get update
        sudo apt-get upgrade
