'on':
  github:
    branches:
      only: main
jobs:
'on':
  github:
    branches:
      only: main
jobs:
  Install:
    resources:
      instance-type: C5
    outputs:
      00-source:
        type: volume  # Changer 'volume' en 'dataset' si nécessaire
    uses: script@v1
    with:
      script: |
        # Installer les dépendances nécessaires
        apt-get update && apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
        # Cloner le dépôt 00
        git clone https://github.com/00/00.git /00
        # Copier les sources dans l'output
        cp -r /00 /outputs/00-source
        image: tensorflow/tensorflow:1.14.0-py3
