'on':
  github:
    branches:
      only: main
jobs:
  HelloWorld:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: python /inputs/repo/hello.py
      image: ubuntu:latest
